### ISSUE TITLE
When Using Visual Studio 15 2017, an error occurs during the PostBuildEvent

### ISSUE THREAD

**Issue by Mikerah** [cppan/webcam_demo#1]
When building this example, I got the following error in powershell,
PostBuildEvent:
  setlocal
  cppan_copy_deps_Release.
  if %errorlevel% neq 0 goto :cmEnd
  :cmEnd
  endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
  :cmErrorLevel
  exit /b %1
  :cmDone
  if %errorlevel% neq 0 goto :VCEnd
  :VCEnd
  'cppan_copy_deps_Release.' is not recognized as an internal or external command,
  operable program or batch file.

It occurs when building the copy-dependencies project. The way I fixed was by opening the solution generated by cppan. Then going in properties for the copy-dependencies project and removing the line "cppan_copy_deps_Release.". After that, I was able to run the example without any issues.

**Comment by egorpugin** [comment]
Many fixes were made since that.
I've checked and this example works fine.
